### ISSUE TITLE
different rating of same movie

### ISSUE THREAD

**Issue by armaanbadhan** [PEC-CSS/MovieDroid#171]
the rating of same movie is different in detail view and in list view

<div>
<img src="https://user-images.githubusercontent.com/66007619/222805173-1b04529f-0a6f-4d75-b121-4446f1c8389f.png" height=400>
<img src="https://user-images.githubusercontent.com/66007619/222805181-0df79a4c-bac4-4cbc-be39-43e84f9407e3.png" height=400>
</div>

**Comment by ken1000minus7** [comment]
Hmm I see, have you checked the cause of this

**Comment by armaanbadhan** [comment]
the rating in the list view is from users userList which is outdated, the one is detail view is fetched everytime user opens that

**Comment by ken1000minus7** [comment]
For this we can change this line i believe, instead of copying the whole object we can just take the rating given by user and the status
https://github.com/PEC-CSS/MovieDroid/blob/b21568b74f9699647659aacc22fb4c080e83a756/app/src/main/java/com/pec_acm/moviedroid/mainpage/search/SearchFragment.kt#L100-L105

**Comment by armaanbadhan** [comment]
yup, theres no point of storing the score

**Comment by ken1000minus7** [comment]
should i assign

**Comment by armaanbadhan** [comment]
yessirr

**Comment by ken1000minus7** [comment]
nyc
